include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/gen/*
    - lib/models/*
linter:
  rules:
    public_member_api_docs: false
    prefer_if_elements_to_conditional_expressions: false
    prefer_single_quotes: false
    lines_longer_than_80_chars: false
    sort_constructors_first: false
